config/core/urls.py
from django.urls import path

from config.core import views
from config.core.views import login, core_page
from django.conf import settings

app_name = 'core'
urlpatterns = [
    path('', core_page, name='core_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from config.core.views import page_logout, appointment_scan, appointment_voice, core_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('config.core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout', page_logout, name='logout'),
    path('appointment_scan', appointment_scan, name='appointment_scan'),
    path('appointment_voice', appointment_voice, name='appointment_voice'),
    path('core', core_page, name='core_page'),
    path('i18n/', include('django.conf.urls.i18n')),
]

config/core/models.py
import datetime

import django.contrib.auth
from django.db import models
from ordered_model.models import OrderedModel
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator


# Create your models here.

class Material(OrderedModel):
    code_material = models.CharField(max_length=64, unique=True, verbose_name=_('code'))
    code_material_related = models.ForeignKey(
        'Material',
        on_delete=models.PROTECT,
        related_name="mat_related_material",
        verbose_name=_('related material'),
        null=True,
        blank=True)

    def __str__(self):
        return f'{self.code_material}'


class Box(OrderedModel):
    code_box = models.CharField(
        max_length=24,
        unique=True, verbose_name=_('code'),
        validators=[MinLengthValidator(24)])
    description = models.TextField(max_length=64, verbose_name=_('description'))
    is_empty = models.BooleanField(default=False, verbose_name=_('empty'))

    def __str__(self):
        return self.code_box


class Appointment(OrderedModel):
    box = models.ForeignKey(
        Box, on_delete=models.PROTECT, related_name="log_box", verbose_name=_('box'))

    material = models.ForeignKey(
        Material, on_delete=models.PROTECT, related_name="log_material", verbose_name=_('material'))

    related_material = models.ForeignKey(
        Material,
        on_delete=models.PROTECT,
        related_name="log_related_material",
        verbose_name=_('related material'),
        null=True,
        blank=True)

    creator = models.ForeignKey(User, on_delete=models.PROTECT, editable=False, verbose_name=_('creator'))

    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))

    def __str__(self):
        return f'{self.box} - {self.material}'

    def created_updated(model, request):
        # obj = model.objects.latest('pk')
        obj = model
        if (obj.creator is None) or (obj.creator == ""):
            obj.creator = request.user
        obj.updated_by = request.user
        obj.save()

    # def save_model(self, request, obj, form, change):
    #     # Passar request como argumento.
    #     obj.created_updated(request)
    #     super().save_model(request, obj, form, change)

config/core/forms.py
import json

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Box, Appointment, User, Material
from django import forms


class AppointmentFormScan(forms.ModelForm):
    box = forms.CharField(min_length=24, max_length=24, required=True, label=_('Box Number'))

    material = forms.CharField(max_length=64, required=True, label=_('Material Number'))

    class Meta:
        model = Appointment
        exclude = ["box", "material"]

    def clean_box(self):
        b = self.cleaned_data['box']
        if not Box.objects.filter(code_box=b).exists():
            raise forms.ValidationError(_("The box is invalid"))
        if Box.objects.filter(code_box=b, is_empty=False):
            raise forms.ValidationError(_("The box {b} is not empty").format(b=b))

        return b

    def clean_material(self):
        m = self.cleaned_data['material']
        if not Material.objects.filter(code_material=m).exists():
            raise forms.ValidationError(_("The Material is invalid"))

        return m


class AppointmentFormVoice(forms.ModelForm):
    box = forms.CharField(min_length=4, max_length=4, required=True, label=_('Box Number'))

    material = forms.CharField(max_length=64, required=True, label=_('Material Number'))

    class Meta:
        model = Appointment
        exclude = ["box", "material"]

    def clean_box(self):
        b = self.cleaned_data['box']
        get_boxes = Box.objects.filter(code_box__endswith=b)  # get_boxes é uma lista
        if get_boxes:
            if len(get_boxes) > 1:
                box_list = ""
                for boxes in get_boxes:
                    box_list += f"{boxes.code_box}, "
                raise forms.ValidationError(_(
                    "There's more than 1 box with {b}: \n {box_list}").format(b=b, box_list=box_list)
                                            )
            elif get_boxes.filter(is_empty=False):
                box_list = ""
                for boxes in get_boxes:
                    box_list += f"{boxes.code_box}, "
                raise forms.ValidationError(_("The box {box_list} is not empty").format(box_list=box_list))
        else:
            raise forms.ValidationError(_("The box is invalid"))

        return b

    def clean_material(self):
        m = self.cleaned_data['material']
        if not Material.objects.filter(code_material=m).exists():
            raise forms.ValidationError(_("The Material is invalid"))

        return m

config/core/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AppointmentFormScan, AppointmentFormVoice
from .models import Box, Material, Appointment
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from config.core.forms import AppointmentFormScan


def core_page(request):
    return render(request, "core/core.html")


def login(request):
    response = redirect('core_page')
    return response


def page_logout(request):
    if request.method == "POST":
        logout(request)

    return redirect("/")


@login_required
def appointment_scan(request):
    form_scan = AppointmentFormScan(request.POST or None)
    if request.method == 'POST':
        if form_scan.is_valid():
            material_code = form_scan.cleaned_data['material']
            box_code = form_scan.cleaned_data['box']
            new_appointment = form_scan.save(commit=False)
            new_appointment.box = Box.objects.filter(code_box=box_code).first()

            new_appointment.material = Material.objects.filter(
                code_material=material_code).first()

            new_appointment.related_material = Material.objects.filter(
                code_material=new_appointment.material.code_material_related).first()

            new_appointment.creator = request.user
            new_appointment.save()
            Box.objects.filter(code_box=box_code).update(is_empty=False)
            form_scan = AppointmentFormScan()
            messages.success(request, _('Appointment Done'))

    context = {'form_scan': form_scan}
    return render(request, 'core/appointment_scan.html', context)


@login_required
def appointment_voice(request):
    form_voice = AppointmentFormVoice(request.POST or None)
    if request.method == 'POST':
        if form_voice.is_valid():
            box_code = form_voice.cleaned_data['box']
            material_code = form_voice.cleaned_data['material']
            new_appointment = form_voice.save(commit=False)
            new_appointment.box = Box.objects.filter(code_box__endswith=box_code).first()
            new_appointment.material = Material.objects.filter(
                code_material=material_code).first()

            new_appointment.related_material = Material.objects.filter(
                code_material=new_appointment.material.code_material_related).first()

            new_appointment.creator = request.user
            new_appointment.save()
            Box.objects.filter(code_box__endswith=box_code).update(is_empty=False)
            form_voice = AppointmentFormVoice()
            messages.success(request, _('Appointment Done'))

    context = {'form_voice': form_voice}
    return render(request, 'core/appointment_voice.html', context)

config/core/templates/core/appointment_scan.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Appointment - Scan{% endblock title %}</title>

    <meta name="author" content="Rodrigo Guedes">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <style>
        .errorlist {
            color: #e50404;
        }
    </style>
</head>
<body>
{% if user.is_authenticated %}
    <form class="mt-2" method="post">
        <h5>{% trans 'Scan' %}</h5>
        {% include 'core/messages.html' %}
        {% csrf_token %}
        <div>
            <input type="text" placeholder="{{ form_scan.box.label }}" name="{{ form_scan.box.html_name }}"
                   maxlength="{{ form_scan.box.field.max_length}}" minlength="{{ form_scan.box.field.min_length }}"
                   class="form-control"
                   id="{{ form_scan.box.id_for_label }}" value="{{ form_scan.box.data|default_if_none:'' }}" required>
        </div>
        {{ form_scan.box.errors }}
        <div class="mt-2">
            <input type="text" name="{{ form_scan.material.html_name }}" placeholder="{{ form_scan.material.label }}"
                   class="form-control"
                   maxlength="{{ form_scan.material.field.max_length }}" id="{{ form_scan.material.id_for_label }}" required
                   value="{{ form_scan.material.data|default_if_none:'' }}">
        </div>
        {{ form_scan.material.errors }}
        <div class="d-grid gap-2 mt-2">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
        </div>
    </form>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-primary btn-lg btn-block">LOGIN</a>
{% endif %}
</div>
</body>
</html>

config/core/templates/core/appointment_voice.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Appointment - Voice{% endblock title %}</title>

    <meta name="author" content="Rodrigo Guedes">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <style>
        .errorlist {
            color: #e50404;
        }
    </style>

</head>
<body>
{% if user.is_authenticated %}
    <form class="mt-2" method="post">
        <h5>{% trans 'Voice' %}</h5>
        {% include 'core/messages.html' %}
        {% csrf_token %}
        <div>
            <input type="text" placeholder="{{ form_voice.box.label }}" name="{{ form_voice.box.html_name }}"
                   class="form-control"
                   maxlength="{{ form_voice.box.field.max_length }}" minlength="{{ form_voice.box.field.min_length }}"
                   id="{{ form_voice.box.id_for_label }}" value="{{ form_voice.box.data|default_if_none:'' }}" required>
        </div>
        {{ form_voice.box.errors }}
        <div class="mt-2">
            <input type="text" name="{{ form_voice.material.html_name }}" placeholder="{{ form_voice.material.label }}"
                   maxlength="{{ form_voice.material.field.max_length }}" id="{{ form_voice.material.id_for_label }}" required
                   value="{{ form_voice.material.data|default_if_none:'' }}" class="form-control">
        </div>
        {{ form_voice.material.errors }}
        <div class="d-grid gap-2 mt-2">
            <button type="submit" id="button" class="btn btn-primary">
                {% trans 'Save' %}
            </button>
        </div>
    </form>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-lg btn-block">LOGIN</a>
{% endif %}
</div>
</body>
</html>

config/core/templates/core/appontment.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Appointment{% endblock title %}</title>

    <meta name="author" content="Rodrigo Guedes">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
<style>
    label {
        display: contents;
    }
</style>
</head>
<body class="mt-2">
{% if user.is_authenticated %}
    <form class="mt-2" action="." method="post">
        <h2>Appointment</h2>
        {% csrf_token %}
{#        {{ form.as_div }}#}
        <div>
            <label for="{{ form.box.id_for_label }}">Box:</label>
        </div>
        <div>
            <input type="text" placeholder="{{form.box.label}}" name="{{ form.box.html_name }}"
                   maxlength="{{ form.box.max_length }}" minlength="{{form.box.min_length}}"
                   id="{{ form.box.id_for_label }}" value="{{ form.box.data|default_if_none:'' }}" required>
        </div>
        {{ form.box.errors }}
        <div class="mt-2">
            <label for="{{ form.material.id_for_label }}">Material:</label>
        </div>
        <div>
            <input type="text" name="{{ form.material.html_name }}" placeholder="{{ form.material.label }}"
                   maxlength="{{ form.material.max_length }}" id="{{ form.material.id_for_label }}" required
                   value="{{ form.material.data|default_if_none:'' }}">
        </div>
        {{ form.material.errors }}
        <div class="mt-2">
            <button type="submit" class="botao_apt">Save</button>
        </div>
    </form>
    <div class="mt-3">
    <form action="{% url 'logout' %}" method="POST" id="logout" class="btn">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-lg btn-block">LOGIN</a>
{% endif %}
</div>
</body>
</html>

config/core/templates/core/appontment0.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Appointment{% endblock title %}</title>

    <meta name="author" content="Rodrigo Guedes">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
<style>
    label {
        display: contents;
    }
</style>
</head>
<body class="mt-2">
{% if user.is_authenticated %}
    <form class="mt-2" action="." method="post">
        <h2>Appointment</h2>
        {% csrf_token %}
{#        {{ form.as_div }}#}
        <div>
            <label for="id_box">Box:</label>
        </div>
        <div>
            <input type="text" placeholder="{{form.box.label}}" name="box"
                   maxlength="{{ form.box.max_length }}" minlength="{{form.box.min_length}}"
                   required id="id_box" value="{{ form.box.data|default_if_none:'' }}">
            {{ form.box.max_length }}
        </div>
        {{ form.box.errors }}
        <div class="mt-2">
            <label for="id_material">Material:</label>
        </div>
        <div>
            <input type="text" name="material" placeholder="{{ form.material.label }}"
                   maxlength="{{ form.material.max_length }}" required id="id_material"
                   value="{{ form.material.data|default_if_none:'' }}">
        </div>
        {{ form.material.errors }}
        <div class="mt-2">
            <button type="submit" class="botao_apt">Save</button>
        </div>
    </form>
    <div class="mt-3">
    <form action="{% url 'logout' %}" method="POST" id="logout" class="btn">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-lg btn-block">LOGIN</a>
{% endif %}
</div>
</body>
</html>

config/core/templates/core/appontment1.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Appointment{% endblock title %}</title>

    <meta name="author" content="Rodrigo Guedes">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
<style>
    label {
        display: contents;
    }
    .errorlist{
        color: red;
    }
</style>
</head>
<body class="mt-2">
{% if user.is_authenticated %}
    <form class="mt-2" action="." method="post">
        <h2>Appointment</h2>
        {% csrf_token %}
        <div>
            <label for="{{ form.box.id_for_label }}">Box:</label>
        </div>
        <div>
            {{ form.box }}
            {{ form.box.errors }}
        </div>
        <div class="mt-2">
            <label for="{{ form.material.id_for_label }}">Material:</label>
        </div>
        <div>
            {{ form.material }}
            {{ form.material.errors }}
        </div>
        <div class="mt-2">
            <button type="submit" class="botao_apt">Save</button>
        </div>
    </form>
    <div class="mt-3">
    <form action="{% url 'logout' %}" method="POST" id="logout" class="btn">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
{% else %}
    <a href="{% url 'login' %}" class="btn btn-lg btn-block">LOGIN</a>
{% endif %}
</div>
</body>
</html>

config/core/templates/core/core.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>Appointment - Menu</title>

</head>

<body>
<div style=" text-align: center;">
    {% if user.is_authenticated %}

        <h5>Menu</h5>
        <div>
            <a href="{% url 'appointment_scan' %}" id="id_scan" class="btn btn_custom btn-danger">{% trans 'Scan' %}</a>
            <br/>
        </div>
        <div class="mt-2">
            <a href="{% url 'appointment_voice' %}" id="id_voice" class="btn btn_custom btn-primary">{% trans 'Voice' %}</a>
            <br/>
        </div>
        <div class="mt-2">
            <form action="{% url 'logout' %}" method="POST" id="logout">
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn_custom btn-secondary">
            </form>
        </div>
    {% else %}
        <br/>
        <a href="{% url 'login' %}" class="btn btn_custom btn-primary">LOGIN</a>

    {% endif %}
    </div>
</div>

</body>

</html>

config/core/templates/core/messages.html
{% load i18n %}
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}